name: coneccionone
description: "Sistema de gestión para servicio técnico de celulares."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # FIREBASE
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10

  # UI / DISEÑO
  glassmorphism: ^3.0.0
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter

  # FUNCIONALIDADES
  share_plus: ^13.1.0
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  pasteboard: ^0.2.0
  image_picker: ^1.1.2
  audioplayers: ^6.1.0
  speech_to_text: ^7.0.0
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: WhiskeyGirlsCondensedItalic
      fonts:
        - asset: assets/fonts/whiskeygirlscondital.ttf
