// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbqZVnlTiNvUBXY1-mJI3dlNNPX497WYY',
    appId: '1:804098380999:web:49e2474a7412df21a9dae2',
    messagingSenderId: '804098380999',
    projectId: 'coneccionone-a9442',
    authDomain: 'coneccionone-a9442.firebaseapp.com',
    storageBucket: 'coneccionone-a9442.firebasestorage.app',
    measurementId: 'G-K8PXR4QQHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS8MV3IIOdmujWM6Q73zWicghKJjfYfVs',
    appId: '1:804098380999:android:08e189c69e6c0d1ea9dae2',
    messagingSenderId: '804098380999',
    projectId: 'coneccionone-a9442',
    storageBucket: 'coneccionone-a9442.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9xVKZS6Ed5_rU47WOU8mmJSm4WjE64hc',
    appId: '1:804098380999:ios:4850fa010518ee02a9dae2',
    messagingSenderId: '804098380999',
    projectId: 'coneccionone-a9442',
    storageBucket: 'coneccionone-a9442.firebasestorage.app',
    iosBundleId: 'com.example.coneccionone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbqZVnlTiNvUBXY1-mJI3dlNNPX497WYY',
    appId: '1:804098380999:web:8a69b811f4171f38a9dae2',
    messagingSenderId: '804098380999',
    projectId: 'coneccionone-a9442',
    authDomain: 'coneccionone-a9442.firebaseapp.com',
    storageBucket: 'coneccionone-a9442.firebasestorage.app',
    measurementId: 'G-6KB7Y2ENGT',
  );

}